spring:
  datasource:
    # driver-class-name: org.postgresql.Driver
    driver-class-name: oracle.jdbc.driver.OracleDriver
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/pet-clinic
    username: prod_user
    password: prod_password
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true